[book]
title = "The Rust Performance Book"
authors = ["Nicholas Nethercote"]
src = "src"
language = "zh"
multilingual = false

[build]
create-missing = false

[rust]
edition = "2018"

[output.html]
curly-quotes = true
default-theme = "rust"
git-repository-url = "https://github.com/Blues-star/perf-book-zh/"
site-url = "https://nnethercote.github.io/perf-book/"
